# Generated by Django 4.2.10 on 2024-07-23 17:17

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Some description about this event')),
                ('spun_speed', models.CharField(choices=[('10', '10'), ('50', '50'), ('100', '100'), ('200', '200'), ('500', '500')], default='10', help_text='Speed to move over names', max_length=3)),
                ('spun_time', models.CharField(choices=[('10', '10'), ('25', '25'), ('50', '50'), ('100', '100'), ('250', '250'), ('500', '500')], default='10', help_text='Speed time took to move', max_length=3)),
                ('event_type', models.CharField(choices=[('private', 'Private')], default='private', help_text="There is only one event for now 'Private'", max_length=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='[draft = not visible, published = visible online, completed = event ended]', max_length=25)),
                ('spun_on', models.DateTimeField(blank=True, help_text='Spin/Lucky draw date and time', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucky_draw.event')),
            ],
            options={
                'unique_together': {('token_number', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 250*250 and format must be png image file', keep_meta=True, null=True, quality=75, scale=None, size=[250, 250], upload_to='results/winners/')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lucky_draw.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lucky_draw.participant')),
            ],
        ),
    ]
